language: php
php:
  - 5.2
  - 5.3
  - 5.4

env:
  - NO_INTERACTION=1

before_script:
  - sh -c "wget http://leveldb.googlecode.com/files/leveldb-1.4.0.tar.gz"
  - sh -c "tar zxvf leveldb-1.4.0.tar.gz"
  - sh -c "cd leveldb-1.4.0 && make"
  - sh -c "mkdir lib && cp libleveldb* lib/"
  - sh -c "cd - && phpize"
  - sh -c "./configure --with-leveldb=$PWD/leveldb-1.4.0"
  - sh -c "make"

script: make test

notifications:
  email:
    - reeze.xia@gmail.com
