language: php

php:
  - 7.0

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 LEVELDB_VERSION=1.7.0
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 LEVELDB_VERSION=1.15.0

before_script: sh travis/prepare.sh

script: sh travis/run-test.sh

notifications:
  email:
    - reeze.xia@gmail.com
